version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/venv
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cakecup
      - JWT_SECRET=your-secret-key
      - ENVIRONMENT=development
    depends_on:
      - db
    command: uvicorn main:application --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cakecup
    ports:
      - "5432:5432"

volumes:
  postgres_data: 